version: '3'

services:
  shopDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 3307:3306
    networks:
      - shopnet
  adminerShop:
    image: adminer
    ports:
      - 8085:8080
    networks:
      - shopnet
  shopDBMigration:
    image: shopdbmigration
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      shopDB:
        condition: service_healthy
    networks:
      - shopnet
  owner:
    image: owner
    environment:
      - DATABASE_URL=shopDB
      - SPARK_URL=sparkapp
    depends_on: [shopDBMigration, sparkapp]
    ports:
      - 5001:5001
    networks:
      - shopnet
  customer:
    image: customer
    environment:
      - DATABASE_URL=shopDB
      - GANACHE_URL=ganache
    depends_on: [shopDBMigration, ganache]
    ports:
      - 5002:5002
    networks:
      - shopnet
  courier:
    image: courier
    environment:
      - DATABASE_URL=shopDB
      - GANACHE_URL=ganache
    depends_on: [shopDBMigration, ganache]
    ports:
      - 5003:5003
    networks:
     - shopnet
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - shopnet
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - shopnet
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - shopnet
  sparkapp:
    image: sparkapp
    depends_on: [spark-master, spark-worker-1, spark-worker-2]
    environment:
      - ENABLE_INIT_DAEMON=false
      - DATABASE_IP=shopDB
      - SPARK_SUBMIT_ARGS=--driver-class-path /app/mysql-connector-j-8.0.33.jar --jars /app/mysql-connector-j-8.0.33.jar
      - PRODUCTION=True
    ports:
      - 8000:8000
    networks:
      - shopnet
  ganache:
    image: trufflesuite/ganache-cli
    ports: 
      - 8545:8545
    networks:
      - shopnet
networks:
  shopnet:
  

    