version: '3'

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_URL=authentication
    ports:
      - 3307:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
    